go.mod, go.sum, ui/service.go, ui/web/template/channel.html, ui/web/template/channelgroups.html, ui/web/template/channels.html, ui/web/template/channelthings.html, ui/web/template/channelusers.html, ui/web/template/group.html, ui/web/template/groupchannels.html, ui/web/template/groupusers.html, ui/web/template/member.html, ui/web/template/thing.html, ui/web/template/thingchannels.html, ui/web/template/thingusers.html, ui/web/template/user.html
Update the UI to change based on a user's permissions. Some components on the UI will be disabled based on the permissions that a user has over the given entity
- Resolves #
=> NOISSUE- Update Permissions

ui/api/endpoint.go, ui/api/logging.go, ui/api/metrics.go, ui/api/requests.go, ui/api/transport.go, ui/service.go, ui/web/static/css/styles.css, ui/web/static/js/infinitescroll.js, ui/web/template/channelusers.html, ui/web/template/domain.html, ui/web/template/domains.html, ui/web/template/groupusers.html, ui/web/template/login.html, ui/web/template/navbar.html, ui/web/template/thingusers.html
Switch from using organization to domain in Magistrala
- Resolves #24
=> MG-24 - Switch from Organization to Domain

ui/api/transport.go, ui/web/static/css/styles.css, ui/web/static/js/errors.js, ui/web/static/js/forms.js, ui/web/static/js/update.js, ui/web/static/js/validation.js, ui/web/template/channel.html, ui/web/template/channels.html, ui/web/template/group.html, ui/web/template/groups.html, ui/web/template/login.html, ui/web/template/thing.html, ui/web/template/things.html, ui/web/template/user.html, ui/web/template/users.html
Updates the javascript functions for update and validation scripts to facilitate border highlighting and also incorporate login page.
- Resolves #25
=> MG-25 - Update javascript functions for update and validation scripts

ui/api/endpoint.go, ui/api/logging.go, ui/api/metrics.go, ui/api/requests.go, ui/api/transport.go, ui/service.go, ui/web/static/css/styles.css, ui/web/template/bootstrap.html, ui/web/template/bootstraps.html, ui/web/template/breadcrumb.html, ui/web/template/channel.html, ui/web/template/channelgroups.html, ui/web/template/channels.html, ui/web/template/channelthings.html, ui/web/template/channelusers.html, ui/web/template/domain.html, ui/web/template/group.html, ui/web/template/groupchannels.html, ui/web/template/groups.html, ui/web/template/groupusers.html, ui/web/template/member.html, ui/web/template/messagesread.html, ui/web/template/navbar.html, ui/web/template/terminal.html, ui/web/template/thing.html, ui/web/template/thingchannels.html, ui/web/template/things.html, ui/web/template/thingusers.html, ui/web/template/user.html, ui/web/template/users.html
Add breadcrumbs to the UI pages for easier page tracking
- Resolves #23
=> MG-23 - Add breadcrumbs

.github/workflows/build.yml, Makefile
Update build ci to push to docker hub instead of GitHub registry
NOISSUE
- Resolves #
=> NOISSUE - Update build CI

Makefile, docker/docker-compose.yml
fix the docker image build name
NOISSUE
- Resolves #
=> NOISSUE - Fix docker image name

Makefile
fix renaming of service from `magistrala-ui` to `ui` in `.phony` in the makefile
NOISSUE
- Resolves #
=> NOISSUE -Fix makefile .PHONY naming of service

ui/web/template/login.html
fix login form reset when successfully submitted. Removal of the `form.reset()` function that temporarily makes the UI page go to a login page with the form reset
- Resolves #46
=> MG-46 - Fix login form reset when successfully submitted

ui/service.go, ui/web/template/group.html
Enable a user to see the parent group of the group they are viewing in view group page
- Resolves #43
=> MG-43 - Add parent to view group params list

ui/api/endpoint.go, ui/api/logging.go, ui/api/metrics.go, ui/api/requests.go, ui/api/transport.go, ui/service.go, ui/web/template/user.html
Add's update user role functionality to the UI for the super admin
- Resolves #40
=> MG-40 - Add Update user role functionality

ui/api/transport.go, ui/web/template/bootstrap.html
- fix the bootstrap API endpoint used in `endpoints.go` to `/bootstraps` instead of `/bootstrap` which will lead to the error page since there is no such API endpoint.
- fix bootstrap update which was failing due to the editable cells not having the field class which prevented the javascript file from detecting the element
NOISSUE
=> NOISSUE - Fix bootstrap 

ui/service.go
This is a bug fix
This handles errors in domains functions assign, unassign and domain.
None
=> NOISSUE - Fix assign user domain error

go.mod, go.sum, ui/web/template/channel.html, ui/web/template/group.html, ui/web/template/thing.html
fix unnecessary horizontal scroll in thing, group and channel view pages
- Resolves #56
=> MG-56 - Fix unnecessary horizontal scroll

ui/web/static/css/styles.css
fix the max height for metadata in a table row to accommodate two or three key-value pairs
noissue
=> NOISSUE - Fix metadata max-height

ui/web/static/css/styles.css
Remove the documentation button link when the screen size is small.
- Resolves #16 
Full screen: 
Small screen:
=> MG-16 - Make header responsive

ui/web/template/bootstraps.html, ui/web/template/channelgroups.html, ui/web/template/channels.html, ui/web/template/channelthings.html, ui/web/template/channelusers.html, ui/web/template/groupchannels.html, ui/web/template/groups.html, ui/web/template/groupusers.html, ui/web/template/invitations.html, ui/web/template/members.html, ui/web/template/messagesread.html, ui/web/template/navbar.html, ui/web/template/thingchannels.html, ui/web/template/things.html, ui/web/template/thingusers.html, ui/web/template/users.html
this will support addition of cancel buttons to the modal facilitating easier navigation in the modal
Update modal structures to facilitate addition of cancel buttons. This enables easier navigation for a user while using the modals
NOISSUE
=> NOISSUE - Update modal structures

ui/web/template/domains.html
In list domains, Added status column
- Related Issue # https://github.com/absmach/magistrala/issues/220
Related to PR in Magistrala https://github.com/absmach/magistrala/pull/248
=> MG220 - Add domain status in list domains

ui/api/requests.go
remove `channelId` and `thingKey` validation from readmessage api, since they are not required in the request.
They will be checked in service.go to request for messages.
fix messageRead page not working, since the variables passed in the request body were not compulsory. This bug was brought about by the validation errors pr, which introduced validation for said variables.
This is checked in this code: https://github.com/absmach/magistrala-ui/blob/e814c464c513602c61f13b17fe6a17b91ef41f62/ui/service.go#L1591C2-L1596C3
NOISSUE
=> NOISSUE - Fix messageRead page not working

ui/api/transport.go
removes multiple condition checks resulting in header being writen more than once
Resolves #57 
this function needs a refactor to clean it up
=> UI-57 - Fix superfluous header writing

ui/service.go, ui/web/static/css/styles.css, ui/web/template/breadcrumb.html, ui/web/template/channelgroups.html, ui/web/template/channelthings.html, ui/web/template/channelusers.html, ui/web/template/groupchannels.html, ui/web/template/groupusers.html, ui/web/template/thingchannels.html, ui/web/template/thingusers.html
Upgrade the breadcrumbs format to be able to take in any number of levels
- Resolves #78
=> MG-78 - Update breadcrumbs format

ui/api/transport.go
Update the code for checking the expiry time in claims
NOISSUE
=> NOISSUE - Update checking claims expiry time

ui/web/static/css/styles.css, ui/web/template/channel.html, ui/web/template/channelgroups.html, ui/web/template/channelthings.html, ui/web/template/channelusers.html, ui/web/template/group.html, ui/web/template/groupchannels.html, ui/web/template/groupusers.html, ui/web/template/thing.html, ui/web/template/thingchannels.html, ui/web/template/thingusers.html, ui/web/template/user.html
Update the styling of the inner tables that had not been updated to the latest changes
- Resolves #74
=> MG-74 - Update metadata styling for the inner tables

ui/api/endpoint.go, ui/api/logging.go, ui/api/metrics.go, ui/api/requests.go, ui/api/transport.go, ui/service.go, ui/web/static/css/styles.css, ui/web/static/js/formatjson.js, ui/web/static/js/update.js, ui/web/template/bootstrap.html, ui/web/template/bootstraps.html, ui/web/template/channel.html, ui/web/template/channels.html, ui/web/template/domain.html, ui/web/template/group.html, ui/web/template/thing.html, ui/web/template/user.html
update bootstrap service to include deleting a bootstrap, updating the state of the bootstrap and displaying the state of the bootstrap
update bootstrap service to include:
1.  deleting a bootstrap
2. updating the state of a bootstrap
3. selecting channels when adding a bootstrap instead of manually entering the channel ID's
- Resolves #70
=> MG-70 - Update bootstrap service

cmd/ui/main.go, ui/api/logging.go
- Update our logger from using Magistrala logger to using the go slog package. 
- It also updates the log messages structure to using attributes for the arguments passed instead of them being incorporated in the message.
- Resolves #84
=> MG-84 - Update logger to use slog package

ui/web/template/tablefooter.html, ui/web/template/tableheader.html
Updates how the links for the table` page number`, `status`, and `items per page` are updated. They will now accept any query parameters currently present in the URL before creating the request.
- Resolves #75 
To be merged after #67
=> MG-75 -  Improve table header and footer

ui/jsonObject.go, ui/web/static/css/dashboards.css, ui/web/static/js/dashboards.js
Implement resizing of the widget by the user during edit mode
- Resolves #100
=> MG-100 - Widget resizing

ui/api/logging.go
Update logger args variable to be of type `[]any` instead of `[]interface{}`
NOISSUE
=> NOISSUE - update Logger variable type

ui/api/transport.go
Remove unused code that checks for an error
NOISSUE
=> NOISSUE - Remove unused code

ui/web/templates/dashboard.html
Fix resizing bug allowing a user to properly resize a widget on first creation of a dashboard layout
- Resolves #112
=> MG-112 - Fix resizing bug 

.github/dependabot.yml, .github/workflows/ci.yaml, README.md, ui/web/static/css/styles.css, ui/web/templates/navbar.html, ui/web/templates/things.html, ui/web/templates/users.html
Signed-off-by: Rodney Osodo <28790446+rodneyosodo@users.noreply.github.com>
- **Chores**
- Updated Dependabot configuration for weekly npm package updates.
- **Documentation**
- Added badges for Docker and CI GitHub actions.
- Updated code formatting instructions with Prettier.
No issue
=> NOISSUE - Fix Prettier

ui/api/endpoint.go, ui/api/errors.go, ui/api/logging.go, ui/api/metrics.go, ui/api/requests.go, ui/api/transport.go, ui/service.go, ui/web/static/js/forms.js, ui/web/templates/login.html, ui/web/templates/registration.html, ui/web/templates/updatepassword.html
Implements registration page
No issue
=> NOISSUE - Implement registration page

.golangci.yml, ui/api/endpoint.go, ui/api/logging.go, ui/api/metrics.go, ui/api/requests.go, ui/api/transport.go, ui/service.go
Signed-off-by: Rodney Osodo <28790446+rodneyosodo@users.noreply.github.com>
- **Refactor**
- Streamlined API by removing unnecessary `token` parameters from several methods, enhancing security and simplifying usage.
- Removed unused fields and parameters across various components, improving performance and maintainability.
- **Chores**
- Updated linter settings in `.golangci.yml` to enforce higher code quality standards.
No issue
=> NOISSUE - Check for unused params

.github/workflows/ci.yaml, ui/api/endpoint.go
The endpoint functions for managing channel members and groups in the UI service have been refactored. The changes include updating `golangci-lint` version and removing unused variables. The modified functions now remove the unused context parameter and perform validation checks on requests before processing them.
No issue
=> NOISSUE - Pin the version of `golangci-lint`

ui/web/static/css/dashboards.css, ui/web/static/js/singleDashboard.js, ui/web/templates/dashboard.html
Adds a placeholder to the canvas during initialization if there is no widget to be placed on the canvas.
- Related Issue #99 
- Resolves #
depends on #108
=> NOISSUE - Add placeholder to the canvas with no widget

cmd/ui/main.go, postgres/init.go, ui/api/endpoint.go, ui/api/logging.go, ui/api/metrics.go, ui/api/requests.go, ui/api/transport.go, ui/charts.go, ui/service.go, ui/web/static/js/singleDashboard.js
Fix the issue where when a user saves an empty canvas the `nowidgetpaceholder` is no longer being displayed.
NOISSUE
- [ x No, and this is why:
=> NOISSUE - Fix nowidget placeholder

ui/api/endpoint.go, ui/api/logging.go, ui/api/metrics.go, ui/api/requests.go, ui/api/transport.go, ui/service.go
- Improved consistency and clarity in API request handling and logging by updating field names and method signatures.
- Introduced a new `Message` struct for clearer communication within services.
No issue
=> NOISSUE - Improve DTOs

ui/api/transport.go, ui/web/static/css/dashboards.css, ui/web/templates/dashboard.html
Fix the widget card CSS to only affect the widget cards and not any other card that will be added to the dashboards page
NOISSUE
=> NOISSUE - Fix chart CSS

ui/charts.go, ui/web/templates/charts/arealinechartmodal.html, ui/web/templates/charts/barchartmodal.html, ui/web/templates/charts/donutmodal.html, ui/web/templates/charts/dynamicdatachartmodal.html, ui/web/templates/charts/gaugemodal.html, ui/web/templates/charts/horizontalbarchartmodal.html, ui/web/templates/charts/linechartmodal.html, ui/web/templates/charts/piechartmodal.html, ui/web/templates/charts/speedgaugemodal.html, ui/web/templates/charts/stackedlinechartmodal.html, ui/web/templates/charts/tempgaugemodal.html
Modify chart modals to sync with individual charts
- Resolves #111
=> MG-111- Modify Chart modals

ui/web/templates/charts/alarmcountmodal.html, ui/web/templates/charts/alarmstablemodal.html, ui/web/templates/charts/doublebarchartmodal.html, ui/web/templates/charts/entitiestablemodal.html, ui/web/templates/charts/entitycountmodal.html, ui/web/templates/charts/labelmodal.html, ui/web/templates/charts/multibarchartmodal.html, ui/web/templates/charts/multigaugemodal.html, ui/web/templates/charts/multiplelinechartmodal.html, ui/web/templates/charts/progressbarmodal.html, ui/web/templates/charts/shareddatasetmodal.html, ui/web/templates/charts/stepchartmodal.html, ui/web/templates/charts/valuecardmodal.html
Modifys existing chart modals and adds an appearance tab.
- Related Issue #146
- Resolves #111
=> MG-111 - Modify chart modals and apperance tab

ui/service.go, ui/web/templates/domains.html, ui/web/templates/thingusers.html
- [] Refactor
Update bug fix to remove the member option for the groups and channels share option and only allow this for domains. Also remove the relation input option for thing sharing since it is only one option.
NOISSUE
=> NOISSUE - Update Relations

ui/web/static/js/singleDashboard.js, ui/web/templates/dashboard.html
this removes all the widgets from the canvas
Add the remove all widgets functionality that allows a user to clear the whole canvas with one button instead of having to delete individual widgets
- Resolves #158
=> MG-158 - Clear dashboard

ui/web/static/js/singleDashboard.js
Removes the grid layout from being saved, since we save the grid items, they are saved with their positions in the grid. Hence, when they are being loaded they are loaded to the position they were at.
NOISSUE
=> NOISSUE - Don't save the grid layout 

ui/api/transport.go
Add a domain login middleware that checks the token being used to access a page if it contains the domain field. If it does not the user is redirected to the domains page automatically so that they can log into a domain before proceeding
- Resolves #156
=> MG-156 - Add domain login middleware

ui/service.go
There was an existing bug where by we decoded userID from the token without verifying who signed the token. With this, we have moved to using `userProfile` to get userID
No issue
=> NOISSUE - Use `userProfile` to get user ID

cmd/ui/main.go, docker/.env, docker/docker-compose.yml, go.mod, go.sum, internal/postgres/postgres.go, ui/README.md
Signed-off-by: Rodney Osodo <28790446+rodneyosodo@users.noreply.github.com>
- aligns Postgres environment variables used by dashboards
- fixes password bug for Postgres connection
- Update `env` package to use one version `v10`
No issue
=> NOISSUE - Align Postgres Env Variables

ui/api/endpoint.go, ui/api/logging.go, ui/api/metrics.go, ui/api/requests.go, ui/api/transport.go, ui/service.go, ui/web/templates/channelusers.html, ui/web/templates/domains.html, ui/web/templates/groupusers.html, ui/web/templates/invitations.html, ui/web/templates/login.html, ui/web/templates/member.html, ui/web/templates/members.html, ui/web/templates/navbar.html, ui/web/templates/registration.html, ui/web/templates/thingusers.html
- [] Refactor
Updates the session management allowing a user to log in/register either using Magistrala UI or an external provider. The user is then redirected to the domains page with the access and refresh token stored in the cookies. When a user then selects which domain they want to join, the UI acquires new domain tokens and updates the cookies in the browser. Furthermore, we introduce a `session cookie` that saves the user details in the browser. The stored cookies will be secured in the PR addressing issue #182 
NOISSUE
=> NOISSUE - Update session management

Makefile
Fixes `/health` endpoint to return correct details about service health
No issue
```bash
curl -sSiX GET http://0.0.0.0:9095/health
```
Before
```json
{
"status": "pass",
"version": "0.0.0",
"commit": "ffffffff",
"description": "ui service",
"build_time": "1970-01-01_00:00:00",
"instance_id": "19c8f131-63f1-461d-be36-b7cb7bf6edb2"
}
```
After
```json
{
"status": "pass",
"version": "v0.14.0",
"commit": "9b460cb208fa54d28588f596fd0f6afab72b8479",
"description": "ui service",
"build_time": "2024-03-02_01:38:52",
"instance_id": "fa5e06b3-fea4-4bd0-86e5-7f82694fca4c"
}
```
=> NOISSUE - Fix Health Endpoint Response

internal/postgres/postgres.go, ui/web/templates/tablefooter.html
Refactors table footer scripts to stop storing status and limits in local storage and instead use the parameters passed in the data struct during template rendering.
NOISSUE
=> NOISSUE - Update table footer

cmd/ui/main.go, ui/oauth2/google/provider.go, ui/oauth2/oauth2.go
- rename to `oauthProvider`
- add new lines after function definition on the OAuth interface
- rename file to `provider.go`
No issue
=> NOISSUE - Refactor OAuth

ui/web/templates/thingchannels.html
Disables the messaging option on the UI if the readers service is not active on Magistrala.
- Resolves #207
=> MG-207 - Disable messaging if reader not active

ui/api/transport.go
redirect a user to the login page if the cookie is missing or if there is an error with fetching the
cookie from the browser.
- Resolves #205
=> Redirect a user to login page

ui/web/templates/dashboard.html
Remove the body scrollable option when the user triggers the off-canvas option.
NOISSUE
=> NOISSUE - Remove duplicate scroll option.

ui/web/templates/login.html, ui/web/templates/registration.html, ui/web/templates/resetpassword.html, ui/web/templates/updatepassword.html
Add the bootstrap class `col-xxl-3` to refactor login page sizing for extra large screens.
NOISSUE
=> NOISSUE - Add bootstrap class to fix login form resizing

.github/workflows/ci.yaml, README.md, go.sum, ui/service.go, ui/web/templates/navbar.html
Renames from mainflux to magistrala. Update the documentation links both from the UI and the UI documentation. Also add `go mod tidy` check
No issue
=> NOISSUE - Rename Docs Pages

.golangci.yml, Makefile, ui/api/metrics.go
Fix the `install` command to copy the binary as magistrala-ui
Fix the `test` command to remove vendor since we don't use it anymore
Fix the `lint` command to update the `golangci-lint` to use the current linter config and prettier to use `npx`
No issue
=> NOISSUE - Fix `install`, `test` and `lint` commands

docker/.env, ui/README.md
Aligns default env variables from the code to `.env` file and `README` file
No issue
=> NOISSUE - Align Environment Variables

cmd/ui/main.go, docker/Dockerfile, docker/Dockerfile.dev, ui/api/transport.go, ui/service.go
Use `//go:embed` directive to embed static files directly to the go binary making it easier to include html, CSS, javascript and images in the binary
No issue
=> NOISSUE - Embed Static Files to UI Binary

ui/service.go
It updates all the breadcrumbs to be able to use the UI prefix incase it is set.
It also refactors how the URL's for the breadcrumbs are created.
NOISSUE
=> NOISSUE - Fix breadcrumbs links to use prefix

ui/web/templates/channelthings.html, ui/web/templates/groupchannels.html
add prefix provision to the href links for the login and register pages for provider login and register respectively.
Noissue
=> NOISSUE - Add prefix to provider signin and signup links

postgres/dashboards_test.go
Fix the linter as it is failing
=> NOISSUE - Fix failing CI

.golangci.yml, ui/service.go
Fixes uncaught wrap check errors
No issue
=> NOISSUE -  Fix uncaught `wrapcheck` errors

ui/api/transport.go, ui/web/templates/channels.html
Removes the ability for a user to create a channel with another channel as the parent. This is because this is not supported on the magistrala core.
- Resolves #42 
- Resolves #44
=> MG-42 - Remove creation of a channel with a parent channel
